#ifndef _APP_DEFS_
#define _APP_DEFS_
#include "grididea_global.h"

#define OP_MODE_TX      0x10
#define OP_MODE_RX      0x20

#define TX_MODE_SWITCH  0x01
#define TX_MODE_CONTROL 0x02

#define RX_MODE_SWITCH  0x00
#define RX_MODE_CONTROL 0x01

#define RX_GEAR_STEPPER 0x00
#define RX_GEAR_SERVO   0x02

#define RX_VALVE_IO     0x00
#define RX_VALVE_PWM    0x04

#define RX_VALVE_PWM_REV        0x08

#define MODE_TX_CONTROL         (OP_MODE_TX | TX_MODE_CONTROL)
#define MODE_TX_SWITCH          (OP_MODE_TX | TX_MODE_SWITCH)

#define MODE_RX_CONTROL_V1      (OP_MODE_RX | RX_MODE_CONTROL | RX_GEAR_STEPPER | RX_VALVE_IO)
#define MODE_RX_CONTROL_V2      (OP_MODE_RX | RX_MODE_CONTROL | RX_GEAR_SERVO | RX_VALVE_PWM)


enum DATAFLASH_DEF_e{
  APP_SIGNATURE = PARAM_U8,
  APP_SIGNATURE_MAX = APP_SIGNATURE+3,
  BOARDID,
  OP_MODE,
  TX_INTERVAL_MS,
  RF_DATA_RATE_CODE,
  RF_TX_POWER,
  BAUDRATE,
  NOF_UINT8_VARS,
  
  
  DEVICE_ADDR =PARAM_U16,
  DEST_ADDR,
  //TX_COUNTS,
  TIMEOUT_MS,  
  VR_RAW_PT_1,
  VR_RAW_PT_2,
  VR_RAW_PT_3,
  VR_RAW_PT_4,
  VR_ANGLE_PT_1,
  VR_ANGLE_PT_2,
  VR_ANGLE_PT_3,
  VR_ANGLE_PT_4,
  STEPPER_MIN_PPS,
  STEPPER_MAX_PPS,
  PWM_MAP_RAW_PT_1,
  PWM_MAP_RAW_PT_2,
  PWM_MAP_RAW_PT_3,
  PWM_MAP_RAW_PT_4,
  PWM_MAP_COUNTER_PT_1,
  PWM_MAP_COUNTER_PT_2,
  PWM_MAP_COUNTER_PT_3,
  PWM_MAP_COUNTER_PT_4,
  SERVO_MAP_RAW_PT_1,
  SERVO_MAP_RAW_PT_2,
  SERVO_MAP_RAW_PT_3,
  SERVO_MAP_RAW_PT_4,
  SERVO_MAP_COUNTER_PT_1,
  SERVO_MAP_COUNTER_PT_2,
  SERVO_MAP_COUNTER_PT_3,
  SERVO_MAP_COUNTER_PT_4,
  TX_DIO_MASK,
  BLINK_PERIOD_MS,
  TX_LBT_LOW_BOUND,
  TX_LBT_HIGH_BOUND,
  NOF_UINT16_VARS,

  BOARD_SECTION_HW_VERSION = PARAM_U32,
  BOARD_SECTION_FW_VERSION,
  BOARD_SECTION_USERID,
  BOARD_SECTION_FUNCTION_CODE,
  BOARD_SERIAL,

  FIRST_I8 = PARAM_I8,
  NOF_INT8_VARS,

  SPEED_MAP_ANGLE_1=PARAM_I16,
  SPEED_MAP_ANGLE_2,
  SPEED_MAP_ANGLE_3,
  SPEED_MAP_ANGLE_4,
  SPEED_MAP_LOW_1,
  SPEED_MAP_LOW_2,
  SPEED_MAP_LOW_3,
  SPEED_MAP_LOW_4,
  SPEED_MAP_HIGH_1,
  SPEED_MAP_HIGH_2,
  SPEED_MAP_HIGH_3,
  SPEED_MAP_HIGH_4,
  TX_VR_OFFSET,
  TX_BATV_OFFSET,
  NOF_INT16_VARS,

  USER_RAW_OFFSET_CHANNEL_1 = PARAM_I32,
  NOF_INT32_VARS,

  MOTOR_MAP_PPD = PARAM_F32,
  RF_BASE_FREQUENCY,
  TX_VR_GAIN,
  TX_BATV_GAIN,
  NOF_F32_VARS
};

#if (PARAM_INDEX(NOF_INT32_VARS) > NOF_I32_PARAM)
#error "too many U32 definitions"
#endif

#if (PARAM_INDEX(NOF_UINT32_VARS) > NOF_U32_PARAM)
#error "too many U32 definitions"
#endif

#if (PARAM_INDEX(NOF_INT16_VARS) > NOF_I16_PARAM)
#error "too many U32 definitions"
#endif

#if (PARAM_INDEX(NOF_UINT16_VARS) > NOF_U16_PARAM)
#error "too many U32 definitions"
#endif

#if (PARAM_INDEX(NOF_INT8_VARS) > NOF_I8_PARAM)
#error "too many U32 definitions"
#endif

#if (PARAM_INDEX(NOF_U8_VARS) > NOF_U8_PARAM)
#error "too many U32 definitions"
#endif
#if (PARAM_INDEX(NOF_SINGLE_VARS) > NOF_F4_PARAM)
#error "too many U32 definitions"
#endif


enum LIVE_DATA_e{
  LIVD_DATA_CH1_GAIN_CODE = PARAM_U8,
  LIVE_DATA_DIO_STATE = PARAM_U16,
  LIVE_DATA_AIN_CH1,
  LIVE_DATA_AIN_CH2,
  LIVE_DATA_PWM_V1,
  LIVE_DATA_PWM_V2,
  LIVE_DATA_PWM_V3,
  LIVE_DATA_PWM_V4,
  LIVE_DATA_CH1_RAW = PARAM_I32,
  LIVE_DATA_CH1_ENG = PARAM_F32,
};

enum COMMAND_e
{
  CMD_START,
  CMD_STOP,
  CMD_SAVE_NVM,
  CMD_RESTORE_NVM,
  CMD_TX,
  CMD_RX_PACKET,
  CMD_RX_ERROR,
  CMD_RX_LOST,
  CMD_TX_DATA_REQUEST,
  CMD_TX_DONE
};


#endif